#!/usr/bin/env php
<?php

$autoload = realpath(__DIR__."/../vendor/autoload.php");
if (!file_exists($autoload)) {
    $autoload = realpath(__DIR__."/../../../autoload.php");
    if (!file_exists($autoload)) {
        throw new \Exception('Autoload not found. Did you run `composer dump-autload`?');
    }
}
require_once($autoload);


use Symfony\Component\Console\Application;

$application = new Application('Migrate Script by JG', '1.1.0');
$application->add(new \ByJG\DbMigration\Console\ResetCommand());
$application->add(new \ByJG\DbMigration\Console\UpCommand());
$application->add(new \ByJG\DbMigration\Console\DownCommand());
$application->add(new \ByJG\DbMigration\Console\CreateCommand());
$application->run();
